name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build-dependency
      - run: npm run favicons
      - run: npm run legacy
      - run: npm run build
      - run: npm run test:build
